/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List all products
         *
         *     Returns all products in inventory. Optionally filter by availability.
         */
        get: operations["Products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get a single product by ID
         *
         *     Returns detailed product information including all variant options.
         */
        get: operations["Products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Standard error response */
        ErrorResponse: {
            /** @description Error message */
            error: string;
        };
        /** @description A product available for purchase */
        Product: {
            /**
             * Format: int32
             * @description Unique product identifier
             */
            id: number;
            /** @description Product display name */
            name: string;
            /** @description Manufacturer or brand name */
            brand: string;
            /**
             * Format: double
             * @description Price in SEK
             */
            price: number;
            /** @description Whether the product is currently available for purchase */
            available: boolean;
            /**
             * Format: double
             * @description Product weight in kilograms
             */
            weight: number;
            /** @description Available variant options (colors, sizes, etc.) */
            options: components["schemas"]["VariantOption"][];
        };
        /** @description Response containing a list of products */
        ProductListResponse: {
            /** @description Array of products */
            products: components["schemas"]["Product"][];
            /**
             * Format: int32
             * @description Total count of products in response
             */
            total: number;
        };
        /**
         * @description Product variant options (color, power, storage combinations)
         *
         *     Each option represents a purchasable configuration with its
         *     own stock quantity.
         */
        VariantOption: {
            /** @description Available colors for this variant */
            color: string[];
            /** @description Power options in watts (for lighting products) */
            power?: number[];
            /** @description Storage options in GB (for electronics) */
            storage?: string[];
            /**
             * Format: int32
             * @description Stock quantity for this specific combination
             */
            quantity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Products_list: {
        parameters: {
            query?: {
                /** @description Filter by availability status */
                available?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    Products_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
