/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        /** @description Root inventory structure from third-party JSON. */
        InventoryData: {
            items: components["schemas"]["Product"][];
        };
        /** @description A product in the inventory. */
        Product: {
            /** Format: int32 */
            id: number;
            name: string;
            brand: string;
            /** @description Price in SEK (stored as string in JSON) */
            price: string;
            available: boolean;
            /** Format: double */
            weight: number;
            options: components["schemas"]["VariantOption"][];
        };
        ProductListResponse: {
            products: components["schemas"]["Product"][];
            /** Format: int32 */
            total: number;
        };
        /**
         * @description Product variant with optional attributes.
         *     Color can be a single string or array of strings.
         */
        VariantOption: {
            /** @description Color options - can be string or string array in raw JSON */
            color?: string | string[];
            /** @description Power options in watts (for lighting products) */
            power?: number[];
            /** @description Storage options in GB (for electronics) */
            storage?: string[];
            /**
             * Format: int32
             * @description Stock quantity for this variant
             */
            quantity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Products_list: {
        parameters: {
            query?: {
                available?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    Products_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
